name: "Bug report"
description: Create a report to help us improve
body:

  - type: markdown

 - type: input

    id: device_model

    attributes:

      label: Device model

      description: What is your device model? This can usually be found in your device's settings in the "About" section.

      placeholder: (e.g. `OnePlus 8 (IN2010)`, or `SM-G960UZKABST`, etc.)

- type: input

    id: Device

    attributes:

      label: Device

      description: Enter the Device model including the name of the manufacturer

    validations:

      required: true

- type: dropdown

  id: android_version

  attributes:

    label: Android version

    multiple: false

    description: What version of Android are you running?

    options:

      - 12

      - 11

      - 10

      - 9

      - 8.1

      - 8.0

      - 7.1

      - 7.0

      - 6

      - 5.1

      - 5.0

      - 4.4

      - 4.3

      - 4.2

      - 4.1

      - 4.0

  validations:

    required: true

    

Magisk version name: 

Magisk version code: 



