[package]
name = "magiskboot"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
path = "lib.rs"

[build-dependencies]
protobuf-codegen = "3.2.0"
cxx-gen = { workspace = true }

[dependencies]
base = { path = "../base" }
cxx = { path = "../external/cxx-rs" }
protobuf = { workspace = true }
byteorder = { workspace = true }
anyhow = { workspace = true }
