[package]
name = "magiskboot"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
path = "lib.rs"

[build-dependencies]
cxx-gen = { workspace = true }
pb-rs = { workspace = true }

[dependencies]
base = { path = "../base" }
cxx = { path = "../external/cxx-rs" }
byteorder = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
size = { workspace = true }
quick-protobuf = { workspace = true }
